version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: student_db
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_DATABASE: student_db
      MYSQL_USER: linux
      MYSQL_PASSWORD: redhat
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: student_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/student_db
      - SPRING_DATASOURCE_USERNAME=linux
      - SPRING_DATASOURCE_PASSWORD=redhat
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - mysql


  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: student_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
    driver: local
